" be iMproved
set nocompatible

" required by Vundle
filetype off

" load Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" Powerline
Bundle 'Lokaltog/vim-powerline'
" Solarized color scheme
Bundle 'altercation/vim-colors-solarized'
" git wrapper
Bundle 'tpope/vim-fugitive'
" fast file access in vim
Bundle 'git://git.wincent.com/command-t.git'

" set 4 space tabs
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab

" set indent
set smartindent
set autoindent

" show line number
set number

" enable syntax highlighting
syntax enable

" highlight searches
set hlsearch

" enable autocomplete menu
set wildmenu

" enable loading plugin files for file type
" also required by vundle
filetype plugin indent on

" set terminal colors to 256
set t_Co=256

" color scheme
" use degraded 256 color scheme
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" Powerline
set laststatus=2 " always show the status line
