" be iMproved
set nocompatible

" required by Vundle
filetype off

" load Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" Powerline
Bundle 'Lokaltog/vim-powerline'
" Solarized color scheme
Bundle 'altercation/vim-colors-solarized'
" git wrapper
Bundle 'tpope/vim-fugitive'
" fast file access in vim
Bundle 'git://git.wincent.com/command-t.git'
" code search with ack
Bundle 'mileszs/ack.vim'

" enable loading plugin files for file type
" also required by vundle
filetype plugin indent on

" set 4 space tabs
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

" set indent
set autoindent

" keep some space above and below the cursor
set scrolloff=10

" enable the use of mouse
set mouse=a

" enable persistent undos
set undodir=/tmp
set undofile

" show relative line number
set relativenumber

" show colored 80th and 120th column
set colorcolumn=80,120

" show invisibles
set list
set listchars=tab:▸\ ,trail:\ 

" Powerline
set laststatus=2 " always show the status line

" enable autocomplete menu
set wildmenu

" highlight searches
set hlsearch

" set terminal colors to 256
set t_Co=256

" enable syntax highlighting
syntax enable

" color scheme
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

" up and down movements by screen line
nnoremap k gk
nnoremap j gj

" shortcut for typing :noh
nnoremap <Leader><space> :nohlsearch<CR>
