" be iMproved
set nocompatible

" set the character encoding
set encoding=utf-8

" required by Vundle
filetype off

" load Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" Airline
Bundle 'bling/vim-airline'
" Solarized color scheme
Bundle 'altercation/vim-colors-solarized'
" git wrapper
Bundle 'tpope/vim-fugitive'
" fast file access in vim
Bundle 'kien/ctrlp.vim'
" filesystem explorer
Bundle 'scrooloose/nerdtree'
" code search with ack
Bundle 'mileszs/ack.vim'
" easily add/change/delete surroundings
Bundle 'tpope/vim-surround'
" Google Go support
Bundle 'jnwhiteh/vim-golang'

" enable loading plugin files for file type
" also required by vundle
filetype plugin indent on

" set 4 space tabs
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

" language specific indentation
if has('autocmd')
    " html 2 space tabs
    autocmd FileType html* setlocal shiftwidth=2 tabstop=2 softtabstop=2
    " Google Go uses tabs characters and don't need to show invisibles
    autocmd FileType go,godoc setlocal noexpandtab nolist
    " Makefile don't need to show invisibles
    autocmd FileType make setlocal nolist
    " yaml 2 space tabs
    autocmd FileType yaml* setlocal shiftwidth=2 tabstop=2 softtabstop=2
endif

" set indent
set autoindent

" keep some space above and below the cursor
set scrolloff=10

" enable the use of mouse
set mouse=a

if has('persistent_undo')
    " enable persistent undos
    set undodir=/tmp
    set undofile
endif

if exists('+relativenumber')
    " show relative line number
    set relativenumber
else
    " show line number
    set number
endif

if exists('+colorcolumn')
    " show colored 80th and 120th column
    set colorcolumn=80,120
endif

" show invisibles
set list
set listchars=tab:▸\ ,trail:\ 

" Airline
set laststatus=2 " always show the status line
set noshowmode " do not show mode message on last line
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_branch_prefix='⎇  '
let g:airline_theme='solarized'

" CtrlP
let g:ctrlp_map='<Leader>t'

" enable autocomplete menu
set wildmenu

" highlight searches
set hlsearch

" ignore case smartly for searchs
set ignorecase
set smartcase

" set terminal colors to 256
set t_Co=256

" enable syntax highlighting
syntax enable

" color scheme
try
    set background=dark
    let g:solarized_termcolors=256
    colorscheme solarized
catch
    colorscheme desert
endtry

" 100ms key code delay
set ttimeoutlen=100

" up and down movements by screen line
nnoremap k gk
nnoremap j gj

" shortcut for typing :noh
nnoremap <Leader><space> :nohlsearch<CR>

" shortcut for NERDTree
nnoremap <Leader>e :NERDTreeToggle<CR>

" shortcut for Ack
nnoremap <Leader>a :Ack 
