# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="stu"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(vi-mode git command-not-found per-directory-history zsh-syntax-highlighting virtualenv virtualenvwrapper rbenv)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# Disable auto correction
unsetopt correct_all

# Re-enable Ctrl-R backward search.
bindkey -M viins "^R" history-incremental-search-backward
bindkey -M vicmd "^R" history-incremental-search-backward

# Editors
export VISUAL=vim
export EDITOR=$VISUAL

# Update dotfiles.
alias dotfiles-update="$HOME/.dotfiles/scripts/update.sh"

# sudo shortcuts
alias apt-get="sudo apt-get"
alias pacman="sudo pacman"
alias systemctl="sudo systemctl"

# vi is vim
alias vi="vim"

# Set up Google Cloud SDK
if [ -d $HOME/google-cloud-sdk ]; then
    source $HOME/google-cloud-sdk/path.zsh.inc
    source $HOME/google-cloud-sdk/completion.zsh.inc
fi

# Allow termite to open new terminal in the same folder
if [ $TERM = xterm-termite ] && [ -f /etc/profile.d/vte.sh ]; then
    source /etc/profile.d/vte.sh
fi

